language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_264f051ee895_key -iv $encrypted_264f051ee895_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
